// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aagalmtlbshrqatdhkya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZ2FsbXRsYnNocnFhdGRoa3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MDE5NTIsImV4cCI6MjA3ODk3Nzk1Mn0.df96IBoa7d-32VnqXsazbWonwV83Sy1EeefabHC3sYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});