// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjtwwkcraapviwjhuixb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdHd3a2NyYWFwdml3amh1aXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMDQzNjEsImV4cCI6MjA5MTc4MDM2MX0.MZeaH6X9jAeJGTFrGZGqf6MJ3OG-OS9wdxR2D_wJ460";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});